
replace region_name = "1" if region_name == "AHAFO"
replace region_name = "2" if region_name == "ASHANTI"
replace region_name = "3" if region_name == "BONO"
replace region_name = "3" if region_name == "BRONG AHAFO"
replace region_name = "4" if region_name == "BONO.EAST"
replace region_name = "4" if region_name == "BONO EAST"
replace region_name = "5" if region_name == "CENTRAL"
replace region_name = "6" if region_name == "EASTERN"
replace region_name = "7" if region_name == "GREATER.ACCRA"
replace region_name = "7" if region_name == "GREATER ACCRA"
replace region_name = "8" if region_name == "NORTH.EAST"
replace region_name = "8" if region_name == "NORTH EAST"
replace region_name = "9" if region_name == "NORTHERN"
replace region_name = "888" if region_name == "not.reported"
replace region_name = "10" if region_name == "OTI"
replace region_name = "11" if region_name == "SAVANNA"
replace region_name = "12" if region_name == "UPPER.EAST"
replace region_name = "12" if region_name == "UPPER EAST"
replace region_name = "13" if region_name == "UPPER.WEST"
replace region_name = "13" if region_name == "UPPER WEST"
replace region_name = "14" if region_name == "VOLTA"
replace region_name = "15" if region_name == "WESTERN"
replace region_name = "16" if region_name == "WESTERN.NORTH"
replace region_name = "999" if region_name == "NATIONAL"
replace region_name = "15" if region_name == "COASTAL COMMUNITIES" 
destring region_name, replace force
label define region_n 1 "AHAFO" 2	"ASHANTI" 3 "BONO" 4	"BONO.EAST" 5	"CENTRAL" 6	"EASTERN" 7	"GREATER.ACCRA" 8	"NORTH.EAST" 9	"NORTHERN" 888	"not.reported" 10	"OTI" 11	"SAVANNA" 12	"UPPER.EAST" 13	"UPPER.WEST" 14	"VOLTA" 15	"WESTERN" 16	"WESTERN.NORTH " 999 "NATIONAL" 
label values region_name region_n
