replace region_name = "ASHANTI" if region_name == "ASHANTI"
replace region_name = "BONO" if region_name == " Brong Ahafo"
*replace region_name = "BONO" if region_name == "AHAFO"
replace region_name = "BONO" if region_name == "BRONG AHAFO"
replace region_name = "BONO" if region_name == "BRONG.AHAFO"
replace region_name = "NORTHERN" if region_name == " Sudan savannah"
replace region_name = "NORTHERN" if region_name == "NORTHERN GHANA"
replace region_name = "NORTHERN" if region_name == "Northern region_name"
replace region_name = "NORTHERN" if region_name == "Northern savannah"
replace region_name = "NORTHERN" if region_name == "NORTHERNold"
replace region_name = "NORTHERN" if region_name == "UW and NR"
replace region_name = "UPPER EAST" if region_name == " Upper East"
replace region_name = "UPPER WEST" if region_name == " Upper West"
replace region_name = "UPPER WEST" if region_name == " UW SR"
replace region_name = "VOLTA" if region_name == "VOLTAold"
replace region_name = "WESTERN" if region_name == "WESTERNold"