replace org_type = 2 if ImplementingAgencies == "Friends of the Earth/Ghana"
replace org_type = 2 if ImplementingAgencies == "Canadian Feed The Children (CFTC) with Canadian coalition partner Farm Radio International (FRI), local implementing partners Regional Advisory & Information Network Systems (RAINS), Trade Aid Integrated (TAI), Tumu Deanery Regional Integrated Development Programme (TUDRIDEP), and NGO, government and academic technical partners"
replace org_type = 2 if ImplementingAgencies == "Oxfam and PAS-Garu, PARED, ProNet North and NANDRIDEP."
replace org_type = 2 if ImplementingAgencies == "GIZ, John A. Kufuor Foundation, Technoserve (TNS)"
replace org_type = 2 if ImplementingAgencies == "CERATH DEVELOPMENT ORGANIZATION"
replace org_type = 2 if ImplementingAgencies == "GOLDEN EXOTIC LIMITED, VOLTA RIVER ESTATES LTD"
replace org_type = 2 if ImplementingAgencies == "WORLD VISION GHANA"
replace org_type = 2 if ImplementingAgencies == "ACTIONAID GHANA"
replace org_type = 2 if ImplementingAgencies == "CISS - COOPERAZIONE INTERNAZIONALE SUD SUD"
replace org_type = 2 if ImplementingAgencies == "CARE DENMARK"
replace org_type = 2 if ImplementingAgencies == "Rainforest Alliance, Tropenbos International Ghana, EcoCare Ghana & World Vision"
replace org_type = 2 if ImplementingAgencies == "Association of Church Development Projects"
replace org_type = 2 if ImplementingAgencies == "Nasia and Yagaba-Kubori Farmer groups"
replace org_type = 2 if ImplementingAgencies == "ALLIANCE BIODIVERSITY CIAT"
replace org_type = 2 if ImplementingAgencies == " International Crops Research Institute for the Semi-Arid Tropics (ICRISAT) and The Council for Scientific and Industrial Research-Animal Research Institute (CSIR-ARI) "
replace org_type = 2 if ImplementingAgencies == "ACDI-VOCA"
replace org_type = 2 if ImplementingAgencies == "ACDI-VOCA"
replace org_type = 2 if ImplementingAgencies == "ACDI-VOCA"
replace org_type = 2 if ImplementingAgencies == "ACDI-VOCA"
replace org_type = 2 if ImplementingAgencies == "US ForestService/International Programs."
replace org_type = 2 if ImplementingAgencies == "WISHH"
replace org_type = 2 if ImplementingAgencies == "Technoserve"
replace org_type = 2 if ImplementingAgencies == "CNFA, in collaboration with the National Cocoa Producer Association, Kuapa Kokoo Farmers Union and Chemico Limited"
replace org_type = 2 if ImplementingAgencies == "CNFA"
replace org_type = 2 if ImplementingAgencies == "IFDC"
replace org_type = 2 if ImplementingAgencies == "Solidaridad West Africa and Masara N'Arziki Farmers Association"
replace org_type = 2 if ImplementingAgencies == "Solidaridad West Africa"
replace org_type = 2 if ImplementingAgencies == "Form Ghana Ltd"
replace org_type = 2 if ImplementingAgencies == "UNU INRA"
replace org_type = 2 if ImplementingAgencies == "A Rocha Ghana, Client Earth"
replace org_type = 2 if ImplementingAgencies == ""develoPPP.de""
replace org_type = 2 if ImplementingAgencies == "UEMOA's West African Development Bank (BOAD)"
replace org_type = 2 if ImplementingAgencies == "JIRCAS "
replace org_type = 2 if ImplementingAgencies == "JIRCAS, SARI, Tokyo University of Agriculture, Kyoto University, Kagoshima University"
replace org_type = 2 if ImplementingAgencies == "JIRCAS"
replace org_type = 2 if ImplementingAgencies == "AGRA"
replace org_type = 2 if ImplementingAgencies == "GISP, JOSMA, AIC, FRI/C-AVA II; MOTI"
replace org_type = 2 if ImplementingAgencies == "Esoko"
replace org_type = 2 if ImplementingAgencies == "University of Tokyo, United Nations University Institute for the"
replace org_type = 2 if ImplementingAgencies == "Advanced Study of Sustainability, Kyoto University, University"
replace org_type = 2 if ImplementingAgencies == "Natural Resources in Africa"
