replace Region = "NATIONAL" 	if Region == "All Regions"
replace Region = "UPPER WEST" 	if Region == " UW SR"
replace Region = "BRONG AHAFO" 	if Region == "BRONG AHAFO"
replace Region = "BONO" 		if Region == "BONO EAST"
replace Region = "NORTHERN" 	if Region == "NORTH EAST"
replace Region = "BRONG AHAFO" 	if Region == "AHAFO"
replace Region = "WESTERN NORTH" if Region == "WESTERN NORTH"
replace Region = "NORTHERN" 	if Region == "NORTHERN GHANA"
replace Region = "UPPER EAST" 	if Region == " Upper East"
replace Region = "UPPER WEST" 	if Region == " Upper West"
replace Region = "BRONG AHAFO" 	if Region == " Brong Ahafo"
replace Region = "NATIONAL" 	if Region == "National"
replace Region = "UPPER WEST" 	if Region == "UW and NR"
replace Region = "NORTHERN" 	if Region == "Northern savannah"
replace Region = "UPPER EAST" 	if Region == " Sudan savannah"
replace Region = "NATIONAL" 	if Region == "Ghana"
replace Region = "BRONG AHAFO" if Region == "AhR"
replace Region = "BRONG AHAFO" if Region == " AhR"
replace Region = "UPPER WEST" 	if Region == "Upper West Region"
replace Region = "ASHANTI" 		if Region == "AR "
replace Region = "BRONG AHAFO" if Region == "BR"
replace Region = "GREATER ACCRA" if Region == "GR"

replace Region = "ASHANTI" if Region == "ASHANTI"
replace Region = "BONO" if Region == " Brong Ahafo"
replace Region = "BONO" if Region == "AHAFO"
replace Region = "BONO" if Region == "BRONG AHAFO"
replace Region = "BONO" if Region == "BRONG.AHAFO"
replace Region = "NORTHERN" if Region == " Sudan savannah"
replace Region = "NORTHERN" if Region == "NORTHERN GHANA"
replace Region = "NORTHERN" if Region == "Northern Region"
replace Region = "NORTHERN" if Region == "Northern savannah"
replace Region = "NORTHERN" if Region == "NORTHERNold"
replace Region = "NORTHERN" if Region == "UW and NR"
replace Region = "UPPER EAST" if Region == " Upper East"
replace Region = "UPPER WEST" if Region == " Upper West"
replace Region = "UPPER WEST" if Region == " UW SR"
replace Region = "VOLTA" if Region == "VOLTAold"
replace Region = "WESTERN" if Region == "WESTERNold"
replace	Region = "AHAFO" if	Region 	 == "Ahafo"
replace	Region = "AHAFO" if	Region 	 == "AHR"
replace	Region = "National" if	Region 	 == "All"
replace	Region = "ASHANTI" if	Region 	 == "AR"
replace	Region = "ASHANTI" if	Region 	 == "Ashanti"
replace	Region = "BRONG AHAFO" if	Region 	 == "BA"
replace	Region = "BONO EAST" if	Region 	 == "BE"
replace	Region = "BONO" if	Region 	 == "BR"
replace	Region = "BRONG AHAFO" if	Region 	 == "Brong"
replace	Region = "GREATER ACCRA" if	Region 	 == "COASTAL"
replace	Region = "CENTRAL" if	Region 	 == "CR"
replace	Region = "EASTERN" if	Region 	 == "East"
replace	Region = "EASTERN" if	Region 	 == "ER"
replace	Region = "GREATER ACCRA" if	Region 	 == "GA"
replace	Region = "National" if	Region 	 == "GHANA"
replace	Region = "GREATER ACCRA" if	Region 	 == "GR"
replace	Region = "National" if	Region 	 == "national"
replace	Region = "NORTH EAST" if	Region 	 == "NE"
replace	Region = "NORTHERN" if	Region 	 == "Norther"
replace	Region = "NORTHERN" if	Region 	 == "NORTHERN"
replace	Region = "NORTHERN" if	Region 	 == "NR"
replace	Region = "NORTHERN" if	Region 	 == "NS"
replace	Region = "SAVANNA" if	Region 	 == "SAVANNAH"
replace	Region = "SAVANNA" if	Region 	 == "SR"
replace	Region = "UPPER EAST" if	Region 	 == "UE"
replace	Region = "UPPER WEST" if	Region 	 == "UW"
replace	Region = "VOLTA" if	Region 	 == "VR"
replace	Region = "WESTERN" if	Region 	 == "WE"
replace	Region = "WESTERN" if	Region 	 == "West"
replace	Region = "WESTERN NORTH" if	Region 	 == "WN"
replace	Region = "WESTERN" if	Region 	 == "WR"
replace	Region = "OTI" if	Region 	 == "Oti"
replace	Region = "AHAFO" if	Region 	 == " Ahafo"
replace	Region = "AHAFO" if	Region 	 == " AHR"
replace	Region = "National" if	Region 	 == " All"
replace	Region = "ASHANTI" if	Region 	 == " AR"
replace	Region = "ASHANTI" if	Region 	 == " Ashanti"
replace	Region = "BRONG AHAFO" if	Region 	 == " BA"
replace	Region = "BONO EAST" if	Region 	 == " BE"
replace	Region = "BONO" if	Region 	 == " BR"
replace	Region = "BRONG AHAFO" if	Region 	 == " Brong"
replace	Region = "GREATER ACCRA" if	Region 	 == " COASTAL"
replace	Region = "CENTRAL" if	Region 	 == " CR"
replace	Region = "EASTERN" if	Region 	 == " East"
replace	Region = "EASTERN" if	Region 	 == " ER"
replace	Region = "GREATER ACCRA" if	Region 	 == " GA"
replace	Region = "National" if	Region 	 == " GHANA"
replace	Region = "GREATER ACCRA" if	Region 	 == " GR"
replace	Region = "National" if	Region 	 == " national"
replace	Region = "NORTH EAST" if	Region 	 == " NE"
replace	Region = "NORTHERN" if	Region 	 == " Norther"
replace	Region = "NORTHERN" if	Region 	 == " NORTHERN"
replace	Region = "NORTHERN" if	Region 	 == " NR"
replace	Region = "NORTHERN" if	Region 	 == " NS"
replace	Region = "SAVANNA" if	Region 	 == " SAVANNAH"
replace	Region = "SAVANNA" if	Region 	 == " SR"
replace	Region = "UPPER EAST" if	Region 	 == " UE"
replace	Region = "UPPER WEST" if	Region 	 == " UW"
replace	Region = "VOLTA" if	Region 	 == " VR"
replace	Region = "WESTERN" if	Region 	 == " WE"
replace	Region = "WESTERN" if	Region 	 == " West"
replace	Region = "WESTERN NORTH" if	Region 	 == " WN"
replace	Region = "WESTERN" if	Region 	 == " WR"
replace	Region = "OTI" if	Region 	 == " Oti"
replace	Region = "ASHANTI" if	Region 	 == " AR"
replace	Region = "BRONG AHAFO" if	Region 	 == " BAR"
replace	Region = "BONO EAST" if	Region 	 == " BER"
replace	Region = "BONO" if	Region 	 == " BR"
replace	Region = "CENTRAL" if	Region 	 == " CR"
replace	Region = "EASTERN" if	Region 	 == " ER"
replace	Region = "GREATER ACCRA" if	Region 	 == " GA"
replace	Region = "NORTH EAST" if	Region 	 == " NER"
replace	Region = "NORTHERN" if	Region 	 == " NR"
replace	Region = "NORTHERN" if	Region 	 == " NR."
replace	Region = "SAVANNA" if	Region 	 == " SR"
replace	Region = "UPPER EAST" if	Region 	 == " UER"
replace	Region = "UPPER WEST" if	Region 	 == " UWR"
replace	Region = "VOLTA" if	Region 	 == " VR"
replace	Region = "WESTERN NORTH" if	Region 	 == " WNR"
replace	Region = "WESTERN" if	Region 	 == " WR"
replace	Region = "ASHANTI" if	Region 	 == "AR"
replace	Region = "ASHANTI" if	Region 	 == "AR "
replace	Region = "ASHANTI" if	Region 	 == "Ashanti and Eastern regions."
replace	Region = "EASTERN" if	Region 	 == "Ashanti and Eastern regions."
replace	Region = "BRONG AHAFO" if	Region 	 == "BAR"
replace	Region = "BONO EAST" if	Region 	 == "BER"
replace	Region = "BONO" if	Region 	 == "BR"
replace	Region = "BRONG AHAFO" if	Region 	 == "Brong Ahafo Region"
replace	Region = "CENTRAL" if	Region 	 == "CR"
replace	Region = "EASTERN" if	Region 	 == "ER"
replace	Region = "GREATER ACCRA" if	Region 	 == "GR"
replace	Region = "NORTH EAST" if	Region 	 == "NER"
replace	Region = "NORTHERN" if	Region 	 == "Northern Region"
replace	Region = "NORTHERN" if	Region 	 == "NR"
replace	Region = "OTI" if	Region 	 == "OR"
replace	Region = "UPPER EAST" if	Region 	 == "Three Northern Regions in Ghana"
replace	Region = "UPPER WEST" if	Region 	 == "Three Northern Regions in Ghana"
replace	Region = "NORTHERN" if	Region 	 == "Three Northern Regions in Ghana"
replace	Region = "UPPER EAST" if	Region 	 == "UER"
replace	Region = "UPPER WEST" if	Region 	 == "UWR"
replace	Region = "WESTERN NORTH" if	Region 	 == "WNR"
replace Region = "BRONG AHAFO" 	if Region 	== "AHAFO"
replace Region = "NORTHERN" 	if Region 	== "Northern Ghana"
replace Region = "WESTERN" 		if Region 	== "WESTERN NORTH"
drop if Region == "No"
drop if Region == "nil"
drop if Region == "(old regions)"
replace Region = "NATIONAL" if Region == "National"
replace Region = "SAVANNA" 		if Region == "SAVANNAH ECOLOGICAL ZONES"
*replace Region = "" 			if Region == ""	